apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-app-source
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.dev/abd-rahim11/tekton-pipeline-example-app 
