apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-env-configmap
data:
  # Replace ARGOCD_SERVER with your ArgoCD server name 
  ARGOCD_SERVER: localhost:8082 #<Argo CD server address>
  ARGOCD_APPLICATION_NAME: tekton-pipeline-app
  ARGOCD_APPLICATION_REVISION: HEAD

