apiVersion: v1
kind: Secret
metadata:
  name: docker-user-auth
  annotations:
    tekton.dev/docker-0: https://index.docker.io/abderrahim
type: kubernetes.io/basic-auth

---

apiVersion: v1
kind: Secret
metadata:
  name: git-app-repo-user-pass
  annotations:
    tekton.dev/git-0: https://github.com/abd-rahim11/docker-2048
type: kubernetes.io/basic-auth


---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-env-secret

---
apiVersion: v1
kind: Secret
metadata:
  name: github-trigger-secret


