---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: tekton-argocd-build-deploy-pipeline
spec:
  resources:
    - name: git-app-source
      type: git
    - name: docker-target
      type: image
  tasks:
    - name: build-docker-image
      taskRef:
        name: build-docker-image
      params:
        - name: pathToDockerFile
          value: /workspace/git-app-source/Dockerfile
        - name: pathToContext
          value: /workspace/git-app-source
      resources:
        inputs:
          - name: git-app-source
            resource: git-app-source
        outputs:
          - name: docker-target
            resource: docker-target
    - name: sync-application
      taskRef:
        name: argocd-task-sync-and-wait
      runAfter:
        - build-docker-image
      params:
        - name: flags
          value: --insecure # needed in this example only because the Argo CD server is locally hosted