apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Kustomize will add the namespace and labels to all files being kustomized
namespace: tekton-argocd-example
commonLabels:
  pipeline: tekton
  deploy: argocd

resources:
- credentials/pipeline-admin-role.yaml
- credentials/triggers-admin-role.yaml
- credentials/build-task-cm.yml
- credentials/argocd-task-cm.yml
#- PipelineRessources/docker-resource.yaml
#- PipelineRessources/git-app-resource.yaml
- tasks/build-task.yaml
- tasks/argocd-task.yaml
- pipelines/build-deploy-pipeline.yaml
- triggers/build-deploy-trigger.yaml
