apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: argocd-task-sync-and-wait
spec:
  description: >-
    This task syncs (deploys) an Argo CD application and waits for it to be healthy.
  params: 
    - name: flags
      default: --
    - name: argocd-version
      default: v2.0.5
  stepTemplate:
    name: argocd server details
    envFrom:
      - configMapRef:
          name: argocd-env-configmap  # used for Argocd server address 
      - secretRef:
          name: argocd-env-secret  # used for authentication (username/password or auth token)
  steps:
    - name: argocd-app-sync
      image: argoproj/argocd:$(params.argocd-version)
      script: |
        argocd login $ARGOCD_SERVER --grpc-web-root-path /argo-cd --username $ARGOCD_USERNAME --password $ARGOCD_PASSWORD
        argocd app sync $ARGOCD_APPLICATION_NAME --revision $ARGOCD_APPLICATION_REVISION $(params.flags) 
        argocd app wait $ARGOCD_APPLICATION_NAME --health $(params.flags) 
