apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-docker-image
spec:
  inputs:
    resources:
      - name: git-app-source
        type: git
    params:
      - name: pathToDockerFile
        type: string
        description: The path to the dockerfile to build
        default: /workspace/git-app-source/Dockerfile
      - name: pathToContext
        type: string
        description: The build context used by Kaniko
        default: /workspace/git-app-source
  outputs:
    resources:
      - name: docker-target
        type: image

  stepTemplate:
    name: Docker image details
    envFrom:
      - configMapRef:
          name: argocd-env-configmap 

  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v0.15.0
      # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
      env:
        - name: "DOCKER_CONFIG"
          value: "/tekton/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(inputs.params.pathToDockerFile)
        - --destination=$(outputs.resources.builtImage.url)/$(DOCKER_IMAGE_NAME):$(DOCKER_TAG)
        - --context=$(inputs.params.pathToContext)
